name: quiz
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_math_fork:
    git:
      url: https://github.com/simpleclub/flutter_math.git
      ref: "6e84b607c5c0e00dd1f3d4bd30ef3f1628053328"
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
     - assets/questions.json


