name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    if: contains(github.event.head_commit.message, 'build:') || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze || true

      - name: Run all tests
        run: flutter test

      - name: Build release APK
        run: flutter build apk --release

      - name: List APKs
        run: ls -l build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
