name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    if: contains(github.event.head_commit.message, 'build:') || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze || true

      - name: Run tests
        run: flutter test test/quiz_controller_test.dart

      - name: Build release APK
        run: flutter build apk --release

      - name: List APKs
        run: ls -l build/app/outputs/flutter-apk/

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Rename APK with version
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-$VERSION.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-${{ env.VERSION }}.apk